

services:
  # # MongoDB Service
  # mongo:
  #   image: mongo:5.0
  #   container_name: mongo
  #   ports:
  #     - "27017:27017" 
  #   volumes:
  #     - mongo-data:/data/db 
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password

    # Backend Service (Node.js/Express)
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "3001:3001"
    environment:
      MONGO_URL: 'mongodb+srv://user_01:KGP8RV@cluster0.3obsxd7.mongodb.net/Home_Rentals?retryWrites=true&w=majority'
    volumes:
      - ./server:/usr/src/app
    command: npm run start

  # Frontend Service (React)
  client:
    build:
      context: ./client 
    container_name: client
    ports:
      - "3002:3002"  
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      REACT_APP_API_URL: http://localhost:3002 
      
 


  